export const GET_DATA_FOR_DROPDOWN_SUCCESS = "GET_DATA_FOR_DROPDOWN_SUCCESS";
export const GET_DATA_FOR_DROPDOWN_FAILURE = "GET_DATA_FOR_DROPDOWN_FAILURE";




export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS";
export const GET_ALL_NOTIFICATION_FAILURE = "GET_ALL_NOTIFICATION_FAILURE";

export const GET_WEBSOCKET_CONNECTION_SUCCESS =
  "GET_WEBSOCKET_CONNECTION_SUCCESS";
export const GET_WEBSOCKET_CONNECTION_FAILURE =
  "GET_WEBSOCKET_CONNECTION_FAILURE";




export const GET_STATES_SUCCESS = "GET_STATES_SUCCESS";
export const GET_STATES_FAILURE = "GET_STATES_FAILURE";

export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAILURE = "GET_CITY_FAILURE";

export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS"
export const GET_COUNTRY_FAILURE = "GET_COUNTRY_FAILURE"



export const REMOVE_DEMAND_SUCCESS = "REMOVE_DEMAND_SUCCESS";
export const REMOVE_DEMAND_FAILURE = "REMOVE_DEMAND_FAILURE";

export const DEFAULT_REDUX_SUCCESS="DEFAULT_REDUX_SUCCESS";
export const DEFAULT_REDUX_FAILURE="DEFAULT_REDUX_FAILURE";


export const RESET_GENERIC_DATA = "RESET_GENERIC_DATA";
